# Generated by Django 5.0.2 on 2024-04-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=10)),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('soil_moisture', models.IntegerField()),
            ],
        ),
    ]
